### ISSUE TITLE
go-wrapper has been deprecated and removed from the images using go version 10 and above. 

### ISSUE THREAD

**Issue by razvanh** [pqvst/go-docker-digitalocean-example#1]
Just a FYI :)

https://github.com/docker-library/golang/pull/205

**Comment by pqvst** [comment]
Hmm ok. Thanks for the heads up. What's the new way of doing it? (I'm not actively working with Go at the moment.)

**Comment by razvanh** [comment]
I am not sure what's the best way to do it. At this time I would use `FROM golang:1.9` instead of `FROM golang:latest` :)
